version: '3'

services:
  db_user:
    container_name: db_user
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=db_user
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qyD^Z<y>F9E86u5
    restart: always

  db_static:
    container_name: db_static
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=db_static
      - POSTGRES_USER=django_admin
      - POSTGRES_PASSWORD=d4DPVwTb46,{f?5
    restart: always

  hyperannales:
    build: .
    command: python HyperAnnales/manage.py runserver 127.0.0.1:6094
    volumes:
      - .:/home/HyperAnnales
    expose:
      - 6094
    links:
      - "db_user"
      - "db_static"
    depends_on:
      - db_user
      - db_static