version: '3.4'

services:
  db_user:
    container_name: db_user
    image: postgres:latest
    environment:
      - POSTGRES_DB=db_user
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qyD^Z<y>F9E86u5
      - PGDATA=/data
    volumes:
      - type: volume
        source: db_HA
        target: /data

    networks:
      - db_user_network
    restart: always

  db_static:
    container_name: db_static
    image: postgres:latest
    environment:
      - POSTGRES_DB=db_static
      - POSTGRES_USER=django_admin
      - POSTGRES_PASSWORD=d4DPVwTb46,{f?5
    networks:
      - db_static_network
    restart: always

  hyperannales:
    build: .
    volumes:
      - .:/home/HyperAnnales
    ports:
    - 6094:6094
    networks:
      - db_static_network
      - db_user_network
    depends_on:
      - db_user
      - db_static

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hyperion.tf
      PGADMIN_DEFAULT_PASSWORD: Explosion2023!
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    network:
      - db_user_network
      - db_static_network
    restart: unless-stopped
    depends_on:
      - db_static
      - db_user

networks:
    db_user_network:
      driver: bridge
    db_static_network:
      driver: bridge
    default:
      external:
        name: host

volumes:
  db_HA: