# Generated by Django 3.0.7 on 2020-10-22 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TD', 'blue'), ('Documents', 'green'), ('Controles', 'red'), ('QCM', 'blue'), ('Aide/Cours', 'green')], default=None, max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('place', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=5, unique=True)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='static_files.CategoryFile')),
            ],
        ),
        migrations.CreateModel(
            name='YearFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('active_semester', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='static_files.SemesterFile')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='static_files.School')),
                ('semester', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='static_files.SemesterFile')),
                ('year', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='static_files.YearFile')),
            ],
        ),
        migrations.CreateModel(
            name='StaticFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default=None, max_length=255)),
                ('date', models.DateField()),
                ('filename', models.CharField(default=None, max_length=255)),
                ('weight', models.IntegerField()),
                ('randomkey', models.IntegerField(unique=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='static_files.StaticContent')),
                ('extension', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='static_files.ExtensionFile')),
            ],
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='static_files.StaticFile'),
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='static_files.School'),
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='static_files.SemesterFile'),
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='static_files.SubjectFile'),
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='static_files.YearFile'),
        ),
        migrations.AddField(
            model_name='categoryfile',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='static_files.School'),
        ),
        migrations.AddField(
            model_name='categoryfile',
            name='semester',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='static_files.SemesterFile'),
        ),
        migrations.AddField(
            model_name='categoryfile',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='static_files.SubjectFile'),
        ),
        migrations.AddField(
            model_name='categoryfile',
            name='year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='static_files.YearFile'),
        ),
    ]
