# Generated by Django 3.0.7 on 2020-10-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('static_files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryfile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='categoryfile',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='categoryfile',
            name='year',
        ),
        migrations.RemoveField(
            model_name='staticcontent',
            name='school',
        ),
        migrations.RemoveField(
            model_name='staticcontent',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='staticcontent',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='staticcontent',
            name='year',
        ),
        migrations.AddField(
            model_name='staticcontent',
            name='place',
            field=models.IntegerField(default=0),
        ),
    ]
